### ISSUE TITLE
SyntaxError: invalid token

### ISSUE THREAD

**Issue by ShadGIT** [HorstBaerbel/ubootwrite#1]
Hi, 

When I run your ubootwrite I get the following error:

  File "ubootwrite.py", line 139
    print("Then erase flash: 'erase 9f020000 " +{0:08x}".format(bytes_read), "'.", sep='', file = sys.stderr)
                                                    ^
SyntaxError: invalid token

The invalid token seems to be 08x.

I am using Linux Mint (17.3), and I have tried with python (2.7.6) and python3 (3.4.3).

Any idea what could be the cause?

Thanks!

**Comment by HorstBaerbel** [comment]
Not sure why this pops up now, but try patching it with: print("Then erase flash: 'erase 9f020000 " + "{:08x}".format(bytes_read) + "'.")

**Comment by HorstBaerbel** [comment]
Could you try if this version works for you (rename to .py):
[ubootwrite.py.txt](https://github.com/HorstBaerbel/ubootwrite/files/266797/ubootwrite.py.txt)
I don't have the router here to test anymore...

**Comment by ShadGIT** [comment]
The first patch works for that line, then another similar error pops up:

  File "ubootbug.py", line 141
    print("Then copy from RAM to flash: 'cp.b 80060000 9f020000 " {0:08x}".format(bytes_read), "'.", sep='', file = sys.stderr)
                                                                  ^
SyntaxError: invalid syntax

I don't have the serial adapter here right now but I have run that second version and it runs without errors until no such file or directory /dev/ttyUSB0 (as expected). So i guess it is solved, thanks!!

**Comment by HorstBaerbel** [comment]
Nice. Thanks for testing. I'll commit the second version then.
