### ISSUE TITLE
NameError: name 'serial' is not defined

### ISSUE THREAD

**Issue by vesterc** [HorstBaerbel/ubootwrite#5]
Hi
I'am using last version HorstBaerbel-patch-1
when i run python ubootwrite.py --serial=/dev/ttyUSB0 --write=uboot.bin --addr=0x80060000 --verbose
I get error 
`Traceback (most recent call last):
  File "ubootwrite.py", line 173, in <module>
    main()
  File "ubootwrite.py", line 157, in main
    ser = serial.Serial(options.serial, 115200, timeout=0.1)
NameError: name 'serial' is not defined`
so I change this line     `ser = serial.Serial(options.serial, 115200, timeout=0.1)` to     `ser = Serial(options.serial, 115200, timeout=0.1)` after that 

```
Waiting for a prompt...
Traceback (most recent call last):
  File "ubootwrite.py", line 173, in <module>
    main()
  File "ubootwrite.py", line 169, in main
    memwrite(ser, options.write, int(options.size, 0), int(options.addr, 0), options.verbose, debug)
  File "ubootwrite.py", line 71, in memwrite
    prompt = getprompt(ser, start_addr, verbose)
  File "ubootwrite.py", line 35, in getprompt
    print("Prompt is '" + buf[2:] + "'")
TypeError: can only concatenate str (not "bytes") to str
```
Any ideas?
I'am using ubuntu 20.04  python 3.8.5 pyserial 3.4.

**Comment by HorstBaerbel** [comment]
Hi. Sorry for not being able to help. I'm not maintaining the repo anymore.
